#!/usr/local/bin/node

const fs = require('fs');
const path = require('path');

const version = process.argv[2];

if (!version)
{
  console.error('Usage: update-package-version <version>');
  process.exit(-1);
}

const filepath = path.resolve(__dirname, '..', 'package.json');

const json = require(filepath);

json.version = version;

let contents = JSON.stringify(json, null, 2);
if (contents[contents.length - 1] !== '\n')
  contents += '\n';

fs.writeFileSync(filepath, contents);
